### ISSUE TITLE
Add persisted entity id to JSON-LD payload as @id

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/coalaip-http-api#15]
We currently ignore the persisted ids of returned entities, which makes it very difficult for users to save the results on their own backends as well as use other parts of the interface that require an entity's id (e.g. transferring rights).

Although not technically correct, as we don't support `GET` operations yet (see #14), we can use the `@id` in the returned JSON-LD to denote the persisted id. Doing so results in a relative URL to the current route, which works for `/manifestations` and `/rights`, but will require some special handling for RightsAssignments since its route is `/rights/transfer` (e.g. its `@id` will probably look something like `../rights_assignment/<id>`).

**Comment by TimDaub** [comment]
@sohkai If this is blocking you might wanna add this to: https://github.com/bigchaindb/org/issues/22

**Comment by sohkai** [comment]
@TimDaub actually the PR's available at #16. Transfers are blocked by this, so I treated it as a subtask of its implementation.
